version: '3.3'
services:
   jellyfin:
     image: jellyfin/jellyfin:latest
     ports:
       - 8096:8096
     restart: "no"
     volumes:
       - ./config:/config
       - ./cache:/cache
       - D:\Media:/media